// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clone_prover`, `compute_block_hash_internal`, `compute_transfer_proof_leaf_hash`, `parse_hex_32`, `parse_hex`, `ss58_to_bytes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Derive a wormhole address pair from a mnemonic.
///
/// # Arguments
/// * `mnemonic` - The 24-word BIP39 mnemonic phrase
/// * `purpose` - The purpose index (0 = mobile sends, 1 = miner rewards)
/// * `index` - The address index within the purpose
///
/// # Returns
/// A `WormholePairResult` containing the address, first_hash, and secret.
///
/// # Example
/// ```ignore
/// let result = derive_wormhole_pair(
///     "word1 word2 ... word24".to_string(),
///     1,  // purpose: miner rewards
///     0,  // index: first address
/// )?;
/// println!("Rewards preimage (for --rewards-preimage): {}", result.first_hash_ss58);
/// println!("Wormhole address (on-chain account): {}", result.address);
/// ```
WormholePairResult deriveWormholePair({required String mnemonic, required int purpose, required int index}) =>
    RustLib.instance.api.crateApiWormholeDeriveWormholePair(mnemonic: mnemonic, purpose: purpose, index: index);

/// Convert a first_hash (rewards preimage) to its corresponding wormhole address.
///
/// This is useful for verifying that a given preimage produces the expected address.
///
/// # Arguments
/// * `first_hash_hex` - The first_hash bytes as hex string (with or without 0x prefix)
///
/// # Returns
/// The wormhole address as SS58 string.
String firstHashToAddress({required String firstHashHex}) =>
    RustLib.instance.api.crateApiWormholeFirstHashToAddress(firstHashHex: firstHashHex);

/// Get the wormhole HD derivation path for a given purpose and index.
///
/// # Arguments
/// * `purpose` - The purpose index (0 = mobile sends, 1 = miner rewards)
/// * `index` - The address index within the purpose
///
/// # Returns
/// The full HD derivation path string.
String getWormholeDerivationPath({required int purpose, required int index}) =>
    RustLib.instance.api.crateApiWormholeGetWormholeDerivationPath(purpose: purpose, index: index);

/// Compute the nullifier for a wormhole UTXO.
///
/// The nullifier is a deterministic hash of (secret, transfer_count) that prevents
/// double-spending. Once revealed on-chain, the UTXO cannot be spent again.
///
/// # Arguments
/// * `secret_hex` - The wormhole secret (32 bytes, hex with 0x prefix)
/// * `transfer_count` - The transfer count from NativeTransferred event
///
/// # Returns
/// The nullifier as hex string with 0x prefix.
String computeNullifier({required String secretHex, required BigInt transferCount}) =>
    RustLib.instance.api.crateApiWormholeComputeNullifier(secretHex: secretHex, transferCount: transferCount);

/// Derive the wormhole address from a secret.
///
/// This computes the unspendable account address that corresponds to the given secret.
///
/// # Arguments
/// * `secret_hex` - The wormhole secret (32 bytes, hex with 0x prefix)
///
/// # Returns
/// The wormhole address as SS58 string.
String deriveAddressFromSecret({required String secretHex}) =>
    RustLib.instance.api.crateApiWormholeDeriveAddressFromSecret(secretHex: secretHex);

/// Quantize an amount from planck (12 decimals) to the circuit format (2 decimals).
///
/// The circuit uses quantized amounts for privacy. This function converts
/// a full-precision amount to the quantized format.
///
/// # Arguments
/// * `amount_planck` - Amount in planck (smallest unit, 12 decimal places)
///
/// # Returns
/// Quantized amount (2 decimal places) that can be used in proof outputs.
int quantizeAmount({required BigInt amountPlanck}) =>
    RustLib.instance.api.crateApiWormholeQuantizeAmount(amountPlanck: amountPlanck);

/// Dequantize an amount from circuit format (2 decimals) back to planck (12 decimals).
///
/// # Arguments
/// * `quantized_amount` - Amount in circuit format (2 decimal places)
///
/// # Returns
/// Amount in planck (12 decimal places).
BigInt dequantizeAmount({required int quantizedAmount}) =>
    RustLib.instance.api.crateApiWormholeDequantizeAmount(quantizedAmount: quantizedAmount);

/// Get the batch size for proof aggregation.
///
/// # Arguments
/// * `bins_dir` - Path to circuit binaries directory
///
/// # Returns
/// Number of proofs that must be aggregated together.
BigInt getAggregationBatchSize({required String binsDir}) =>
    RustLib.instance.api.crateApiWormholeGetAggregationBatchSize(binsDir: binsDir);

/// Create a new proof generator.
///
/// This loads ~171MB of circuit data, so it's expensive. Call once and reuse.
///
/// # Arguments
/// * `bins_dir` - Path to directory containing prover.bin and common.bin
Future<WormholeProofGenerator> createProofGenerator({required String binsDir}) =>
    RustLib.instance.api.crateApiWormholeCreateProofGenerator(binsDir: binsDir);

/// Create a new proof aggregator.
///
/// # Arguments
/// * `bins_dir` - Path to directory containing aggregator circuit files
Future<WormholeProofAggregator> createProofAggregator({required String binsDir}) =>
    RustLib.instance.api.crateApiWormholeCreateProofAggregator(binsDir: binsDir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WormholeProofAggregator>>
abstract class WormholeProofAggregator implements RustOpaqueInterface {
  /// Add a proof to the aggregation buffer.
  ///
  /// # Arguments
  /// * `proof_hex` - The serialized proof bytes (hex encoded with 0x prefix)
  Future<void> addProof({required String proofHex});

  /// Aggregate all proofs in the buffer.
  ///
  /// If fewer than `batch_size` proofs have been added, the remaining
  /// slots are filled with dummy proofs automatically.
  ///
  /// # Returns
  /// The aggregated proof.
  Future<AggregatedProof> aggregate();

  /// Get the batch size (number of proofs per aggregation).
  Future<BigInt> batchSize();

  /// Clear the proof buffer without aggregating.
  Future<void> clear();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new proof aggregator from circuit files.
  ///
  /// # Arguments
  /// * `bins_dir` - Path to directory containing aggregator circuit files
  ///
  /// # Returns
  /// A new proof aggregator instance.
  static Future<WormholeProofAggregator> newInstance({required String binsDir}) =>
      RustLib.instance.api.crateApiWormholeWormholeProofAggregatorNew(binsDir: binsDir);

  /// Get the number of proofs currently in the buffer.
  Future<BigInt> proofCount();
}

/// Result of proof aggregation.
class AggregatedProof {
  /// The serialized aggregated proof bytes (hex encoded).
  final String proofHex;

  /// Number of real proofs in the batch (rest are dummies).
  final BigInt numRealProofs;

  const AggregatedProof({required this.proofHex, required this.numRealProofs});

  @override
  int get hashCode => proofHex.hashCode ^ numRealProofs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AggregatedProof &&
          runtimeType == other.runtimeType &&
          proofHex == other.proofHex &&
          numRealProofs == other.numRealProofs;
}

/// Block header data needed for proof generation.
class BlockHeaderData {
  /// Parent block hash (hex encoded).
  final String parentHashHex;

  /// State root of the block (hex encoded).
  final String stateRootHex;

  /// Extrinsics root of the block (hex encoded).
  final String extrinsicsRootHex;

  /// Block number.
  final int blockNumber;

  /// Encoded digest (hex encoded, up to 110 bytes).
  final String digestHex;

  const BlockHeaderData({
    required this.parentHashHex,
    required this.stateRootHex,
    required this.extrinsicsRootHex,
    required this.blockNumber,
    required this.digestHex,
  });

  @override
  int get hashCode =>
      parentHashHex.hashCode ^
      stateRootHex.hashCode ^
      extrinsicsRootHex.hashCode ^
      blockNumber.hashCode ^
      digestHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockHeaderData &&
          runtimeType == other.runtimeType &&
          parentHashHex == other.parentHashHex &&
          stateRootHex == other.stateRootHex &&
          extrinsicsRootHex == other.extrinsicsRootHex &&
          blockNumber == other.blockNumber &&
          digestHex == other.digestHex;
}

/// Configuration loaded from circuit binaries directory.
class CircuitConfig {
  /// Number of leaf proofs in an aggregation batch.
  final BigInt numLeafProofs;

  const CircuitConfig({required this.numLeafProofs});

  /// Load configuration from a circuit binaries directory.
  static Future<CircuitConfig> load({required String binsDir}) =>
      RustLib.instance.api.crateApiWormholeCircuitConfigLoad(binsDir: binsDir);

  @override
  int get hashCode => numLeafProofs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CircuitConfig && runtimeType == other.runtimeType && numLeafProofs == other.numLeafProofs;
}

/// Result of proof generation.
class GeneratedProof {
  /// The serialized proof bytes (hex encoded).
  final String proofHex;

  /// The nullifier for this UTXO (hex encoded) - used to track spent UTXOs.
  final String nullifierHex;

  const GeneratedProof({required this.proofHex, required this.nullifierHex});

  @override
  int get hashCode => proofHex.hashCode ^ nullifierHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratedProof &&
          runtimeType == other.runtimeType &&
          proofHex == other.proofHex &&
          nullifierHex == other.nullifierHex;
}

/// Output assignment for a proof - where the funds go.
class ProofOutputAssignment {
  /// Amount for output 1 (quantized to 2 decimal places).
  final int outputAmount1;

  /// Exit account for output 1 (SS58 address).
  final String exitAccount1;

  /// Amount for output 2 (quantized, 0 if unused).
  final int outputAmount2;

  /// Exit account for output 2 (SS58 address, empty if unused).
  final String exitAccount2;

  const ProofOutputAssignment({
    required this.outputAmount1,
    required this.exitAccount1,
    required this.outputAmount2,
    required this.exitAccount2,
  });

  @override
  int get hashCode => outputAmount1.hashCode ^ exitAccount1.hashCode ^ outputAmount2.hashCode ^ exitAccount2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProofOutputAssignment &&
          runtimeType == other.runtimeType &&
          outputAmount1 == other.outputAmount1 &&
          exitAccount1 == other.exitAccount1 &&
          outputAmount2 == other.outputAmount2 &&
          exitAccount2 == other.exitAccount2;
}

/// Storage proof data for the transfer.
class StorageProofData {
  /// Raw proof nodes from the state trie (each node is hex encoded).
  final List<String> proofNodesHex;

  /// State root the proof is against (hex encoded).
  final String stateRootHex;

  const StorageProofData({required this.proofNodesHex, required this.stateRootHex});

  @override
  int get hashCode => proofNodesHex.hashCode ^ stateRootHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageProofData &&
          runtimeType == other.runtimeType &&
          proofNodesHex == other.proofNodesHex &&
          stateRootHex == other.stateRootHex;
}

/// Error type for wormhole operations
class WormholeError implements FrbException {
  final String message;

  const WormholeError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is WormholeError && runtimeType == other.runtimeType && message == other.message;
}

/// Result of wormhole pair derivation
class WormholePairResult {
  /// The wormhole address as SS58 (the on-chain account)
  final String address;

  /// The raw address bytes (32 bytes, hex encoded)
  final String addressHex;

  /// The first hash / rewards preimage as SS58 (pass to --rewards-preimage)
  final String firstHashSs58;

  /// The first hash / rewards preimage bytes (32 bytes, hex encoded)
  final String firstHashHex;

  /// The secret bytes (32 bytes, hex encoded) - SENSITIVE, needed for ZK proofs
  final String secretHex;

  const WormholePairResult({
    required this.address,
    required this.addressHex,
    required this.firstHashSs58,
    required this.firstHashHex,
    required this.secretHex,
  });

  @override
  int get hashCode =>
      address.hashCode ^ addressHex.hashCode ^ firstHashSs58.hashCode ^ firstHashHex.hashCode ^ secretHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholePairResult &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          addressHex == other.addressHex &&
          firstHashSs58 == other.firstHashSs58 &&
          firstHashHex == other.firstHashHex &&
          secretHex == other.secretHex;
}

/// Opaque handle to a proof generator.
///
/// The generator is expensive to initialize (loads ~171MB of circuit data),
/// so it should be created once and reused for all proof generations.
class WormholeProofGenerator {
  final String binsDir;

  const WormholeProofGenerator({required this.binsDir});

  /// Generate a proof for a wormhole withdrawal.
  ///
  /// # Arguments
  /// * `utxo` - The UTXO to spend
  /// * `output` - Where to send the funds
  /// * `fee_bps` - Fee in basis points
  /// * `block_header` - Block header for the proof
  /// * `storage_proof` - Storage proof for the transfer
  ///
  /// # Returns
  /// The generated proof and nullifier.
  Future<GeneratedProof> generateProof({
    required WormholeUtxo utxo,
    required ProofOutputAssignment output,
    required int feeBps,
    required BlockHeaderData blockHeader,
    required StorageProofData storageProof,
  }) => RustLib.instance.api.crateApiWormholeWormholeProofGeneratorGenerateProof(
    that: this,
    utxo: utxo,
    output: output,
    feeBps: feeBps,
    blockHeader: blockHeader,
    storageProof: storageProof,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new proof generator from circuit files.
  ///
  /// # Arguments
  /// * `bins_dir` - Path to directory containing prover.bin and common.bin
  ///
  /// # Returns
  /// A new proof generator instance.
  static Future<WormholeProofGenerator> newInstance({required String binsDir}) =>
      RustLib.instance.api.crateApiWormholeWormholeProofGeneratorNew(binsDir: binsDir);

  @override
  int get hashCode => binsDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholeProofGenerator && runtimeType == other.runtimeType && binsDir == other.binsDir;
}

/// A wormhole UTXO (unspent transaction output) - FFI-friendly version.
///
/// Represents an unspent wormhole deposit that can be used as input
/// for generating a proof.
class WormholeUtxo {
  /// The secret used to derive the wormhole address (hex encoded with 0x prefix).
  final String secretHex;

  /// Amount in planck (12 decimal places).
  final BigInt amount;

  /// Transfer count from the NativeTransferred event.
  final BigInt transferCount;

  /// The funding account (sender of the original transfer) - hex encoded.
  final String fundingAccountHex;

  /// Block hash where the transfer was recorded - hex encoded.
  final String blockHashHex;

  const WormholeUtxo({
    required this.secretHex,
    required this.amount,
    required this.transferCount,
    required this.fundingAccountHex,
    required this.blockHashHex,
  });

  @override
  int get hashCode =>
      secretHex.hashCode ^
      amount.hashCode ^
      transferCount.hashCode ^
      fundingAccountHex.hashCode ^
      blockHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholeUtxo &&
          runtimeType == other.runtimeType &&
          secretHex == other.secretHex &&
          amount == other.amount &&
          transferCount == other.transferCount &&
          fundingAccountHex == other.fundingAccountHex &&
          blockHashHex == other.blockHashHex;
}
