// Mocks generated by Mockito 5.4.6 from annotations
// in resonance_network_wallet/test/unit/mnemonic_loss_prevention_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:quantus_sdk/src/models/account.dart' as _i4;
import 'package:quantus_sdk/src/models/display_account.dart' as _i5;
import 'package:quantus_sdk/src/services/settings_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i2.SettingsService {
  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Account>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Account>>.value(
              <_i4.Account>[],
            ),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Future<void> saveAccounts(List<_i4.Account>? accounts) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccounts, [accounts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setAccountsToMigrate(List<_i4.Account>? accounts) =>
      (super.noSuchMethod(
            Invocation.method(#setAccountsToMigrate, [accounts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i4.Account> getAccountsToMigrate() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountsToMigrate, []),
            returnValue: <_i4.Account>[],
            returnValueForMissingStub: <_i4.Account>[],
          )
          as List<_i4.Account>);

  @override
  _i3.Future<void> clearAccountsToMigrate() =>
      (super.noSuchMethod(
            Invocation.method(#clearAccountsToMigrate, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setActiveAccount(_i5.DisplayAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.DisplayAccount?> getActiveAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAccount, []),
            returnValue: _i3.Future<_i5.DisplayAccount?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.DisplayAccount?>.value(),
          )
          as _i3.Future<_i5.DisplayAccount?>);

  @override
  _i3.Future<_i4.Account?> getActiveRegularAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveRegularAccount, []),
            returnValue: _i3.Future<_i4.Account?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Account?>.value(),
          )
          as _i3.Future<_i4.Account?>);

  @override
  _i3.Future<_i4.Account?> getAccount({
    required int? walletIndex,
    required int? index,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAccount, [], {
              #walletIndex: walletIndex,
              #index: index,
            }),
            returnValue: _i3.Future<_i4.Account?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Account?>.value(),
          )
          as _i3.Future<_i4.Account?>);

  @override
  _i3.Future<int> getNextFreeAccountIndex(int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getNextFreeAccountIndex, [walletIndex]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, String>> getAddressBook() =>
      (super.noSuchMethod(
            Invocation.method(#getAddressBook, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> saveAddressBook(Map<String, String>? addressBook) =>
      (super.noSuchMethod(
            Invocation.method(#saveAddressBook, [addressBook]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setAddressName(String? address, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setAddressName, [address, name]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getAddressName(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressName, [address]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> removeAddressName(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#removeAddressName, [address]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getHasWallet() =>
      (super.noSuchMethod(
            Invocation.method(#getHasWallet, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isWalletLoggedOut() =>
      (super.noSuchMethod(
            Invocation.method(#isWalletLoggedOut, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  String getMnemonicKey(int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getMnemonicKey, [walletIndex]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getMnemonicKey, [walletIndex]),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.method(#getMnemonicKey, [walletIndex]),
            ),
          )
          as String);

  @override
  _i3.Future<void> setMnemonic(String? mnemonic, int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#setMnemonic, [mnemonic, walletIndex]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getMnemonic(int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getMnemonic, [walletIndex]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteMnemonic(int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMnemonic, [walletIndex]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setReversibleEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setReversibleEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool isReversibleEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isReversibleEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> setReversibleTimeSeconds(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setReversibleTimeSeconds, [seconds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int?> getReversibleTimeSeconds() =>
      (super.noSuchMethod(
            Invocation.method(#getReversibleTimeSeconds, []),
            returnValue: _i3.Future<int?>.value(),
            returnValueForMissingStub: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<void> setBalanceHidden(bool? hidden) =>
      (super.noSuchMethod(
            Invocation.method(#setBalanceHidden, [hidden]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool isBalanceHidden() =>
      (super.noSuchMethod(
            Invocation.method(#isBalanceHidden, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> setCurrencyFlipped(bool? flipped) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrencyFlipped, [flipped]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool isCurrencyFlipped() =>
      (super.noSuchMethod(
            Invocation.method(#isCurrencyFlipped, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> setSelectedFiatCurrency(String? currencyCode) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedFiatCurrency, [currencyCode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearSelectedFiatCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#clearSelectedFiatCurrency, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setSelectedAppLocale(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedAppLocale, [languageCode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearSelectedAppLocale() =>
      (super.noSuchMethod(
            Invocation.method(#clearSelectedAppLocale, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPosModeEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setPosModeEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool isPosModeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isPosModeEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  _i3.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i3.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void setLastPausedTime(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastPausedTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void cleanLastPausedTime() => super.noSuchMethod(
    Invocation.method(#cleanLastPausedTime, []),
    returnValueForMissingStub: null,
  );

  @override
  bool hasOldAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#hasOldAccounts, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i4.Account> getOldAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getOldAccounts, []),
            returnValue: <_i4.Account>[],
            returnValueForMissingStub: <_i4.Account>[],
          )
          as List<_i4.Account>);

  @override
  _i3.Future<void> clearOldAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#clearOldAccounts, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setOldAccountsData(String? jsonData) =>
      (super.noSuchMethod(
            Invocation.method(#setOldAccountsData, [jsonData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void resetForTest() => super.noSuchMethod(
    Invocation.method(#resetForTest, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool referralCheckCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#referralCheckCompleted, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setReferralCheckCompleted() => super.noSuchMethod(
    Invocation.method(#setReferralCheckCompleted, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearReferralCheckCompletedFlag() => super.noSuchMethod(
    Invocation.method(#clearReferralCheckCompletedFlag, []),
    returnValueForMissingStub: null,
  );

  @override
  void setReferralCode(String? code) => super.noSuchMethod(
    Invocation.method(#setReferralCode, [code]),
    returnValueForMissingStub: null,
  );

  @override
  bool hasWatchedQuestsPromo() =>
      (super.noSuchMethod(
            Invocation.method(#hasWatchedQuestsPromo, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setQuestsPromoWatched() => super.noSuchMethod(
    Invocation.method(#setQuestsPromoWatched, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearQuestsPromoWatchedFlag() => super.noSuchMethod(
    Invocation.method(#clearQuestsPromoWatchedFlag, []),
    returnValueForMissingStub: null,
  );

  @override
  bool existingUserSeenPromoVideo() =>
      (super.noSuchMethod(
            Invocation.method(#existingUserSeenPromoVideo, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setExistingUserSeenPromoVideo() => super.noSuchMethod(
    Invocation.method(#setExistingUserSeenPromoVideo, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearExistingUserSeenPromoVideoFlag() => super.noSuchMethod(
    Invocation.method(#clearExistingUserSeenPromoVideoFlag, []),
    returnValueForMissingStub: null,
  );
}
